### ISSUE TITLE
Job doesn't run after PBC creation

### ISSUE THREAD

**Issue by AnurupGuha** [smrg-uob/PeriodicBoundaryCondition#2]
Hi,

I am running an explicit-dynamic analysis in abaqus with a subroutine for hyper-elastic material behavior. I used the plug-in to create PBC between two surfaces in my model. The plug-in does work well and creates the constraint equations for all the node pairs as intended. But when I submit the job, it gets stuck and the time-steps doesn't show up. Is there anything that I need to do with regards to the plug-in.

Thanks!

**Comment by xvheule** [comment]
Is there anything relevant showing up in the message file?

**Comment by mikechy1** [comment]
After launching the PBC plugin, added:

import sys
sys.path.insert (9,
      r'c:/Users/ Mine /abaqus_plugins/PeriodicBoundaryCondition ')
import PeriodicBoundaryCondition_kernel
PeriodicBoundaryCondition_kernel.create_registry ()

to the abaqus.rpy file (of course, there is no * .msg file).
