### ISSUE TITLE
Plugin not works

### ISSUE THREAD

**Issue by mikechy1** [smrg-uob/PeriodicBoundaryCondition#4]
Hi,
After start plugin I've got empty form (see attached). Please help. Thx.
![Image](https://user-images.githubusercontent.com/89173012/129995679-34e1fd51-a0e6-47ab-ae81-c074b3e526e2.png)

**Comment by mikechy1** [comment]
I am attaching a simple model Python code if necessary.
[Model3D.py.txt](https://github.com/smrg-uob/PeriodicBoundaryCondition/files/7026401/Model3D.py.txt)

**Comment by xvheule** [comment]
What is not working exactly?
Have you pressed the "New" button?

I would suggest you go through the [readme](https://github.com/smrg-uob/PeriodicBoundaryCondition/blob/master/README.md).

**Comment by mikechy1** [comment]
Thanks for the reply. As you can see from the picture, the plug-in does not recognize the model, although, according to Readme, it should "When launching the plugin from the menu bar, the following dialog window will show up" ...
After I pressed the "New" button, in Error Log window I got:
Traceback (most recent call last):
  File "c:/.../abaqus_plugins/PeriodicBoundaryCondition\PeriodicBoundaryCondition_plugin.py", line 149, in getNextDialog
    return self.get_next_dialog()
  File "c:/.../abaqus_plugins/PeriodicBoundaryCondition\PeriodicBoundaryCondition_plugin.py", line 37, in get_next_dialog
    return self.get_input_dialog()
  File "c:/.../abaqus_plugins/PeriodicBoundaryCondition\PeriodicBoundaryCondition_plugin.py", line 49, in get_input_dialog
    return PeriodicBoundaryCondition_DB.InputDialog(self, self.STEP_NEW)
  File "c:/.../abaqus_plugins/PeriodicBoundaryCondition\PeriodicBoundaryCondition_DB.py", line 328, in __init__
    self.on_model_selected()
  File "c:/.../abaqus_plugins/PeriodicBoundaryCondition\PeriodicBoundaryCondition_DB.py", line 393, in on_model_selected
    reset_combo_box(self.cbx_part, mdb.models[models[model_index]].parts.keys())
TypeError: list indices must be integers, not NoneType

**Comment by xvheule** [comment]
The dialog on the screenshot shows all Periodic Boundary Conditions currently active on the model, as you have none, it is indeed empty.
The error after clickign the new button tells me you are not using Abaqus 2018. What version of Abaqus are you using?

**Comment by mikechy1** [comment]
Abaqus 6.14.1 . Can you try my model Model3D.py.txt?

**Comment by xvheule** [comment]
No, apologies, this plugin is for Abaqus 2018, which is explitly mentioned in the readme.
It will sadly not work with older versions due to CAE's slightly different code base.
