### ISSUE TITLE
How can we add tensile loading with pbc?

### ISSUE THREAD

**Issue by chandlerchenn** [smrg-uob/PeriodicBoundaryCondition#5]
Hi,

thanks for upload this periodic boundary condition plugin here. I am working on a 3D RVE and I want to apply pbc on it. I followed your implement instruction here:

Apply a periodic boundary condition on the two faces for the first direction without any exempted edges.
Apply a periodic boundary condition on the two faces for the second direction, and apply an exemption for the edges which are shared with the master surface for the first direction on the master and slave surfaces of the second direction (1 edge is exempted on each of the two faces).
Apply a periodic boundary condition on the two faces for the third direction, and apply an exemption for the edges which are shared with the master surface for the first direction or the second direction on the master and slave surfaces of the third direction (2 edges are exempted on each of the two faces).

After successfully add these constraint equations, I met a problem of applying uniaxal tensile loading. Abaqus saying the there is a DoF error at the loading node. Can you kindly suggest me how to add displacement loading in the RVE with periodic boundary condition？

**Comment by xvheule** [comment]
I'm not quite sure how you are doing things, but I have added an example on how to apply uniaxial tensile loading on a cube [here ](https://github.com/smrg-uob/PeriodicBoundaryCondition/tree/master/examples).
